const APP_VERSION = "6.5-smart-import";
const STORAGE = {
  recipes: `karisRecipeBook.recipes.${APP_VERSION}`,
  planner: `karisRecipeBook.planner.${APP_VERSION}`,
  grocery: `karisRecipeBook.grocery.${APP_VERSION}`
};
const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const CATEGORY_EMOJIS = { dinner:"🍝", breakfast:"🍳", lunch:"🥪", dessert:"🍰", snack:"🍿", "slow cooker":"🍲", holiday:"🎄", healthy:"🥗", mexican:"🌮", chicken:"🐔", pasta:"🍝", grill:"🔥", soup:"🥣", other:"📖" };
const sampleRecipes = [
  { id:1, name:"Creamy Garlic Chicken", category:"Dinner", url:"", ingredients:["2 chicken breasts","1 cup heavy cream","4 cloves garlic","1/2 cup parmesan","Salt and pepper"], instructions:["Season chicken on both sides.","Sear chicken until golden.","Add garlic, cream, and parmesan.","Simmer until sauce thickens and chicken is cooked through."], notes:"Good with pasta, rice, or roasted vegetables.", favorite:true },
  { id:2, name:"Easy Cinnamon Roll Casserole", category:"Breakfast", url:"", ingredients:["2 cans cinnamon rolls","4 eggs","1/2 cup milk","1 tsp vanilla","1 tsp cinnamon"], instructions:["Cut cinnamon rolls into pieces.","Whisk eggs, milk, vanilla, and cinnamon.","Pour over rolls in a baking dish.","Bake until puffed and golden."], notes:"Save icing for the top after baking.", favorite:false }
];
let deferredPrompt = null;
const state = {
  activeFilter:"all",
  recipes: loadJson(STORAGE.recipes, sampleRecipes),
  planner: loadJson(STORAGE.planner, Object.fromEntries(DAYS.map(day => [day, ""]))),
  groceryRecipeIds: loadJson(STORAGE.grocery, [])
};
const el = {};
function loadJson(key, fallback) { const saved = localStorage.getItem(key); return saved ? JSON.parse(saved) : fallback; }
function saveJson(key, data) { localStorage.setItem(key, JSON.stringify(data)); }
function saveRecipes() { saveJson(STORAGE.recipes, state.recipes); }
function savePlanner() { saveJson(STORAGE.planner, state.planner); }
function saveGrocerySelection() { saveJson(STORAGE.grocery, state.groceryRecipeIds); }
function cacheElements() { ["pageTitle","greetingText","totalRecipesStat","favoriteRecipesStat","plannedMealsStat","homeCollections","homeAddRecipeBtn","quickImportBtn","fabAddRecipe","recipeModal","modalBackdrop","closeModalBtn","recipeForm","editId","formTitle","saveBtn","cancelEditBtn","name","category","url","ingredients","instructions","notes","importUrl","importText","openSourceBtn","parseTextBtn","clearImportBtn","importStatus","searchInput","categoryChips","categoryOptions","recipeList","recipeCount","showAllRecipesBtn","plannerGrid","clearPlannerBtn","groceryRecipeSelect","addRecipeToGroceryBtn","groceryFromPlannerBtn","copyGroceryBtn","selectedRecipes","groceryList","installBtn","exportBackupBtn","importBackupInput"].forEach(id => el[id] = document.getElementById(id)); }
function getCategoryEmoji(category = "Other") { return CATEGORY_EMOJIS[String(category).toLowerCase()] || "📖"; }
function cleanLines(value) { return value.split("\n").map(item => item.trim()).filter(Boolean); }
function recipeById(id) { return state.recipes.find(recipe => String(recipe.id) === String(id)); }
function categoryCounts() { const counts = {}; state.recipes.forEach(recipe => { const category = recipe.category || "Other"; counts[category] = (counts[category] || 0) + 1; }); return counts; }
function uniqueCategories() { return Object.keys(categoryCounts()).sort(); }
function recipeMatchesSearch(recipe, term) { return [recipe.name, recipe.category, recipe.notes, recipe.ingredients.join(" "), recipe.instructions.join(" ")].join(" ").toLowerCase().includes(term); }
function getVisibleRecipes() { const term = el.searchInput.value.trim().toLowerCase(); return state.recipes.filter(recipe => { const category = (recipe.category || "Other").toLowerCase(); const filterMatch = state.activeFilter === "all" || (state.activeFilter === "favorites" && recipe.favorite) || category === state.activeFilter; return filterMatch && recipeMatchesSearch(recipe, term); }); }
function renderStats() { el.totalRecipesStat.textContent = state.recipes.length; el.favoriteRecipesStat.textContent = state.recipes.filter(recipe => recipe.favorite).length; el.plannedMealsStat.textContent = Object.values(state.planner).filter(Boolean).length; const hour = new Date().getHours(); const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"; el.greetingText.textContent = `${greeting} 👋`; }
function makeCollectionButton(category, count, active = false) { const button = document.createElement("button"); button.className = `collection-card card ${active ? "active" : ""}`; button.innerHTML = `<span>${getCategoryEmoji(category)}</span><strong>${category}</strong><small>${count} ${count === 1 ? "recipe" : "recipes"}</small>`; button.addEventListener("click", () => { state.activeFilter = category.toLowerCase(); switchView("recipesView", "Recipes"); renderAll(); }); return button; }
function renderCollections() { const counts = categoryCounts(); const categories = uniqueCategories(); el.homeCollections.innerHTML = ""; el.categoryChips.innerHTML = ""; el.categoryOptions.innerHTML = ""; if (!categories.length) { el.homeCollections.innerHTML = `<div class="card empty-state">🍴<br>Your cookbook is empty.</div>`; el.categoryChips.innerHTML = `<div class="card empty-state">Add your first recipe to create collections.</div>`; return; } categories.slice(0, 4).forEach(category => el.homeCollections.appendChild(makeCollectionButton(category, counts[category]))); categories.forEach(category => { el.categoryChips.appendChild(makeCollectionButton(category, counts[category], state.activeFilter === category.toLowerCase())); const option = document.createElement("option"); option.value = category; el.categoryOptions.appendChild(option); }); }
function renderRecipes() { const visibleRecipes = getVisibleRecipes(); el.recipeList.innerHTML = ""; el.recipeCount.textContent = `${visibleRecipes.length} ${visibleRecipes.length === 1 ? "recipe" : "recipes"}`; if (!visibleRecipes.length) { el.recipeList.innerHTML = `<div class="card empty-state">🍴<br>No recipes found.<br><br><button class="primary-btn" onclick="openRecipeModal()">Add Recipe</button></div>`; return; } const template = document.getElementById("recipeCardTemplate"); visibleRecipes.forEach(recipe => { const clone = template.content.cloneNode(true); const source = clone.querySelector(".source-link"); clone.querySelector(".recipe-emoji").textContent = getCategoryEmoji(recipe.category); clone.querySelector("h3").textContent = recipe.name; clone.querySelector(".category-pill").textContent = recipe.category || "Other"; clone.querySelector(".favorite-button").textContent = recipe.favorite ? "★" : "☆"; if (recipe.url) source.href = recipe.url; else source.classList.add("hidden"); appendListItems(clone.querySelector("ul"), recipe.ingredients, "li"); appendListItems(clone.querySelector("ol"), recipe.instructions, "li"); clone.querySelector(".notes").textContent = recipe.notes || ""; clone.querySelector(".favorite-button").addEventListener("click", () => toggleFavorite(recipe.id)); clone.querySelector(".delete-btn").addEventListener("click", () => deleteRecipe(recipe.id)); clone.querySelector(".edit-btn").addEventListener("click", () => editRecipe(recipe.id)); clone.querySelector(".copy-btn").addEventListener("click", () => copyRecipe(recipe)); el.recipeList.appendChild(clone); }); }
function appendListItems(parent, items, tagName) { items.forEach(item => { const child = document.createElement(tagName); child.textContent = item; parent.appendChild(child); }); }
function openRecipeModal() { el.recipeModal.classList.remove("hidden"); el.recipeModal.setAttribute("aria-hidden", "false"); document.body.style.overflow = "hidden"; }
function closeRecipeModal() { el.recipeModal.classList.add("hidden"); el.recipeModal.setAttribute("aria-hidden", "true"); document.body.style.overflow = ""; }
function resetForm() { el.recipeForm.reset(); el.importUrl.value = ""; el.importText.value = ""; el.editId.value = ""; el.formTitle.textContent = "Add Recipe"; el.saveBtn.textContent = "Save Recipe"; el.cancelEditBtn.classList.add("hidden"); setImportStatus(""); }
function setImportStatus(message, type = "") { el.importStatus.textContent = message; el.importStatus.className = `import-status ${type}`; }
function parseSmartText() { const text = el.importText.value.trim(); if (!text) { setImportStatus("Paste recipe text first.", "error"); return; } const lines = text.split(/\r?\n/).map(x => x.trim()).filter(Boolean); let title = ""; let ingredientsArr = []; let instructionsArr = []; let mode = "title"; const ingredientHeaders = ["ingredients", "ingredient"]; const instructionHeaders = ["directions", "instructions", "method", "preparation", "steps"]; const stopHeaders = ["nutrition", "reviews", "tips", "notes", "video", "photos", "cook's note"]; for (const rawLine of lines) { const line = rawLine.replace(/^[-*•]\s*/, "").replace(/^\d+[.)]\s*/, "").trim(); const lower = line.toLowerCase().replace(/:$/, ""); if (!title && !ingredientHeaders.includes(lower) && !instructionHeaders.includes(lower) && line.length < 120) { title = line; continue; } if (ingredientHeaders.some(h => lower === h || lower.startsWith(h + ":"))) { mode = "ingredients"; continue; } if (instructionHeaders.some(h => lower === h || lower.startsWith(h + ":"))) { mode = "instructions"; continue; } if (stopHeaders.some(h => lower === h || lower.startsWith(h + ":"))) { mode = "ignore"; continue; } if (mode === "ingredients" && line.length > 1) ingredientsArr.push(line); if (mode === "instructions" && line.length > 1) instructionsArr.push(line); } el.name.value = title || el.name.value || "Imported Recipe"; el.category.value = el.category.value || "Imported"; el.url.value = el.importUrl.value.trim() || el.url.value; el.ingredients.value = ingredientsArr.join("\n"); el.instructions.value = instructionsArr.join("\n"); el.notes.value = el.notes.value || "Imported from pasted recipe text. Review before saving."; setImportStatus(`Parsed ${ingredientsArr.length} ingredients and ${instructionsArr.length} steps. Review before saving.`, ingredientsArr.length && instructionsArr.length ? "success" : "error"); }
function addOrUpdateRecipe(event) { event.preventDefault(); const editId = el.editId.value; const existing = editId ? recipeById(editId) : null; const id = editId ? Number(editId) : Date.now(); const recipe = { id, name: el.name.value.trim(), category: el.category.value.trim() || "Other", url: el.url.value.trim(), ingredients: cleanLines(el.ingredients.value), instructions: cleanLines(el.instructions.value), notes: el.notes.value.trim(), favorite: existing?.favorite || false }; state.recipes = editId ? state.recipes.map(item => String(item.id) === String(editId) ? recipe : item) : [recipe, ...state.recipes]; saveRecipes(); resetForm(); closeRecipeModal(); switchView("recipesView", "Recipes"); renderAll(); }
function editRecipe(id) { const recipe = recipeById(id); if (!recipe) return; el.editId.value = recipe.id; el.name.value = recipe.name; el.category.value = recipe.category; el.url.value = recipe.url || ""; el.ingredients.value = recipe.ingredients.join("\n"); el.instructions.value = recipe.instructions.join("\n"); el.notes.value = recipe.notes || ""; el.formTitle.textContent = "Edit Recipe"; el.saveBtn.textContent = "Update Recipe"; el.cancelEditBtn.classList.remove("hidden"); openRecipeModal(); }
function toggleFavorite(id) { const recipe = recipeById(id); if (recipe) recipe.favorite = !recipe.favorite; saveRecipes(); renderAll(); }
function deleteRecipe(id) { state.recipes = state.recipes.filter(item => String(item.id) !== String(id)); state.groceryRecipeIds = state.groceryRecipeIds.filter(item => String(item) !== String(id)); Object.keys(state.planner).forEach(day => { if (String(state.planner[day]) === String(id)) state.planner[day] = ""; }); saveRecipes(); savePlanner(); saveGrocerySelection(); renderAll(); }
function copyRecipe(recipe) { const text = `${recipe.name}\n\nIngredients:\n${recipe.ingredients.join("\n")}\n\nInstructions:\n${recipe.instructions.map((step, index) => `${index + 1}. ${step}`).join("\n")}\n\nNotes:\n${recipe.notes || ""}`; navigator.clipboard.writeText(text); }
function renderPlanner() { el.plannerGrid.innerHTML = ""; DAYS.forEach(day => { const selectedId = state.planner[day] || ""; const card = document.createElement("article"); card.className = "day-card card"; card.innerHTML = `<h3>${day}</h3><select data-day="${day}"><option value="">Rest / no meal selected</option>${state.recipes.map(recipe => `<option value="${recipe.id}" ${String(recipe.id) === String(selectedId) ? "selected" : ""}>${recipe.name}</option>`).join("")}</select><p class="planned-meal">${selectedId ? recipeById(selectedId)?.name || "" : "Rest / Open"}</p>`; card.querySelector("select").addEventListener("change", event => { state.planner[day] = event.target.value; savePlanner(); renderAll(); }); el.plannerGrid.appendChild(card); }); }
function renderGroceryControls() { el.groceryRecipeSelect.innerHTML = state.recipes.map(recipe => `<option value="${recipe.id}">${recipe.name}</option>`).join(""); el.selectedRecipes.innerHTML = ""; state.groceryRecipeIds.forEach(id => { const recipe = recipeById(id); if (!recipe) return; const pill = document.createElement("button"); pill.className = "selected-pill"; pill.textContent = `${recipe.name} ×`; pill.addEventListener("click", () => { state.groceryRecipeIds = state.groceryRecipeIds.filter(item => String(item) !== String(id)); saveGrocerySelection(); renderGrocery(); }); el.selectedRecipes.appendChild(pill); }); }
function buildGroceryItems() { const items = []; state.groceryRecipeIds.forEach(id => { const recipe = recipeById(id); if (recipe) items.push(...recipe.ingredients.map(item => item.trim().replace(/\s+/g, " "))); }); return Array.from(new Set(items.filter(Boolean))).sort((a, b) => a.localeCompare(b)); }
function renderGroceryList() { const items = buildGroceryItems(); el.groceryList.innerHTML = items.length ? "" : `<div class="card empty-state">🛒<br>Add recipes or build from your meal plan.</div>`; items.forEach(item => { const row = document.createElement("label"); row.className = "grocery-item"; row.innerHTML = `<input type="checkbox"><span>${item}</span>`; row.querySelector("input").addEventListener("change", event => row.classList.toggle("checked", event.target.checked)); el.groceryList.appendChild(row); }); }
function renderGrocery() { renderGroceryControls(); renderGroceryList(); }
function addRecipeToGrocery() { const id = el.groceryRecipeSelect.value; if (id && !state.groceryRecipeIds.some(item => String(item) === String(id))) state.groceryRecipeIds.push(id); saveGrocerySelection(); renderGrocery(); }
function groceryFromPlanner() { state.groceryRecipeIds = Array.from(new Set(Object.values(state.planner).filter(Boolean))); saveGrocerySelection(); renderGrocery(); }
function copyGrocery() { navigator.clipboard.writeText(buildGroceryItems().join("\n")); }
function clearPlanner() { state.planner = Object.fromEntries(DAYS.map(day => [day, ""])); savePlanner(); renderAll(); }
function exportBackup() { const backup = { app:"Karis Recipe Book", version:APP_VERSION, exportedAt:new Date().toISOString(), recipes:state.recipes, planner:state.planner, groceryRecipeIds:state.groceryRecipeIds }; const blob = new Blob([JSON.stringify(backup, null, 2)], { type:"application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `karis-recipe-book-backup-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); }
async function importBackup(event) { const file = event.target.files[0]; if (!file) return; const backup = JSON.parse(await file.text()); state.recipes = Array.isArray(backup.recipes) ? backup.recipes : []; state.planner = backup.planner || Object.fromEntries(DAYS.map(day => [day, ""])); state.groceryRecipeIds = Array.isArray(backup.groceryRecipeIds) ? backup.groceryRecipeIds : []; saveRecipes(); savePlanner(); saveGrocerySelection(); event.target.value = ""; renderAll(); }
function switchView(viewId, title) { document.querySelectorAll(".view").forEach(view => view.classList.remove("active-view")); document.getElementById(viewId).classList.add("active-view"); document.querySelectorAll(".nav-item").forEach(item => item.classList.toggle("active", item.dataset.view === viewId)); el.pageTitle.textContent = title; window.scrollTo({ top:0, behavior:"smooth" }); }
function renderAll() { renderStats(); renderCollections(); renderRecipes(); renderPlanner(); renderGrocery(); }
function registerEvents() { el.recipeForm.addEventListener("submit", addOrUpdateRecipe); el.cancelEditBtn.addEventListener("click", () => { resetForm(); closeRecipeModal(); }); el.closeModalBtn.addEventListener("click", () => { resetForm(); closeRecipeModal(); }); el.modalBackdrop.addEventListener("click", () => { resetForm(); closeRecipeModal(); }); el.parseTextBtn.addEventListener("click", parseSmartText); el.clearImportBtn.addEventListener("click", () => { el.importUrl.value = ""; el.importText.value = ""; setImportStatus(""); }); el.openSourceBtn.addEventListener("click", () => { const source = el.importUrl.value.trim(); if (!source) { setImportStatus("Paste a source URL first.", "error"); return; } window.open(source, "_blank", "noopener"); }); el.searchInput.addEventListener("input", renderRecipes); el.showAllRecipesBtn.addEventListener("click", () => { state.activeFilter = "all"; renderAll(); }); el.clearPlannerBtn.addEventListener("click", clearPlanner); el.addRecipeToGroceryBtn.addEventListener("click", addRecipeToGrocery); el.groceryFromPlannerBtn.addEventListener("click", groceryFromPlanner); el.copyGroceryBtn.addEventListener("click", copyGrocery); el.exportBackupBtn.addEventListener("click", exportBackup); el.importBackupInput.addEventListener("change", importBackup); el.homeAddRecipeBtn.addEventListener("click", openRecipeModal); el.quickImportBtn.addEventListener("click", () => { openRecipeModal(); setTimeout(() => el.importUrl.focus(), 50); }); el.fabAddRecipe.addEventListener("click", openRecipeModal); document.querySelectorAll(".nav-item").forEach(item => item.addEventListener("click", () => switchView(item.dataset.view, item.dataset.title))); document.querySelectorAll("[data-jump]").forEach(item => item.addEventListener("click", () => { if (item.dataset.filter === "favorites") state.activeFilter = "favorites"; switchView(item.dataset.jump, item.dataset.jump === "recipesView" ? "Recipes" : item.textContent.trim()); renderAll(); })); }
function registerInstallPrompt() { window.addEventListener("beforeinstallprompt", event => { event.preventDefault(); deferredPrompt = event; el.installBtn.classList.remove("hidden"); }); el.installBtn.addEventListener("click", async () => { if (!deferredPrompt) return; deferredPrompt.prompt(); await deferredPrompt.userChoice; deferredPrompt = null; el.installBtn.classList.add("hidden"); }); }
function registerServiceWorker() { if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js")); }
function init() { cacheElements(); registerEvents(); registerInstallPrompt(); registerServiceWorker(); renderAll(); }
init();
